### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by yang2bao** [S-H-Y-GitHub/QA#14]
您好，请问代码中的数据怎么下载，

    trainingFile = "data/training.data"
    developFile = "data/develop.data"
    testingFile = "data/testing.data"
    resultFile = "predictRst.score"
    saveFile = "newModel/savedModel"
    trainedModel = "trainedModel/savedModel"
    embeddingFile = "word2vec/zhwiki_2017_03.sg_50d.word2vec"

有链接提供下载吗，期待您的回复，非常谢谢

**Comment by S-H-Y-GitHub** [comment]
可以参考一下之前的issue

**Comment by yang2bao** [comment]
之前的issue并没有数据的信息啊 @S-H-Y-GitHub

**Comment by zengjunjun** [comment]
这他妈就像一个骗子

**Comment by S-H-Y-GitHub** [comment]
我没有得到这些数据的授权，所以不敢公开出去。

之前的issue提供了足够的信息，如果你足够聪明，应该很容易推断出哪里能搞到数据
