### ISSUE TITLE
请问main.py

### ISSUE THREAD

**Issue by moonyoung430** [S-H-Y-GitHub/QA#15]
不好意思，没问完就提交了。。。
您好，我下载了您的源码，发现main.py中有很多数据文件并没有在源码中，请问一下 如果我自己造这些数据的话要，数据需要什么格式的？如果您有提供的话，我可以在哪里下载？
  ==============================================================
我按照data文件夹中readme中的例子造了training.data 但是报错，大致如下
got shape [598455], but wanted [598455, 0].
在加载测试数据之后得到的embedding 是一个长度为598455的列表，但是在加载LSTM网络时，好像需要的shape是[598455,0]???这是什么shape？？  不知道我理解是不是出问题了

**Comment by S-H-Y-GitHub** [comment]
请查看之前的issue

**Comment by moonyoung430** [comment]
之前没有issue啊？？这个源码下的issue是0

**Comment by S-H-Y-GitHub** [comment]
你看，在issue的表格左上角有个0open，15closed，你不妨点一下那个closed试试？

**Comment by xiximeng** [comment]
您好，我看之前closed的issue里面也并没有提供数据，如果因为版权问题数据不能提供的话，能否给个大概的数据格式呢？谢谢

**Comment by S-H-Y-GitHub** [comment]
data目录下的readme文件中有示例
