### ISSUE TITLE
运行程序的时候报找不到文件

### ISSUE THREAD

**Issue by fengjinhai** [S-H-Y-GitHub/QA#2]
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    embedding, word2idx = qaData.loadEmbedding(embeddingFile)
  File "/Users/baidu/fengjinhai/QA-master/qaData.py", line 17, in loadEmbedding
    with open(filename, mode="r", encoding="utf-8") as rf:
FileNotFoundError: [Errno 2] No such file or directory: 'word2vec/zhwiki_2017_03.sg_50d.word2vec'

**Comment by S-H-Y-GitHub** [comment]
这个文件要自己训练，我没有上传，格式见 #1

**Comment by LMdeLiangMi** [comment]
http://doc.okbase.net/robert-dlut/archive/259946.html

**Comment by LMdeLiangMi** [comment]
http://www.cnblogs.com/robert-dlut/p/6586621.html
