### ISSUE TITLE
为什么会出现这个错误呢

### ISSUE THREAD

**Issue by lingmulhy** [S-H-Y-GitHub/QA#22]
正在载入测试数据，大约需要一分钟...
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.226 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    qTest, aTest, _, qIdTest = qaData.loadData(testingFile, word2idx, unrollSteps)
  File "/home/428/lhy/infinite/QA-master/qaData.py", line 73, in loadData
    answerIdx = sentenceToIndex(arr[1].strip(), word2idx, maxLen)
IndexError: list index out of range

数据格式也没有错误，就是示例中所给的那样的

**Comment by lingmulhy** [comment]
这个问题也解决了  谢谢

**Comment by yunhao138** [comment]
您好，同样是这个错误，请问应该怎么解决？
