### ISSUE TITLE
 got shape [598455], but wanted [598455, 0]

### ISSUE THREAD

**Issue by lingmulhy** [S-H-Y-GitHub/QA#23]
为啥会出现这个错误呢   之前的issue也有人有这个问题  但是没有解决方案啊   下面是词向量文件
</s> 0.008005 0.008839 -0.007661 -0.006556 0.002733 0.006042 0.001882 0.000423 -0.007207 0.004437 -0.008713 0.002499 -0.001503 -0.001914 -0.006631 -0.003764 0.005159 0.006051 0.005938 0.003195 0.003090 -0.007605 -0.008192 0.009939 0.007603 0.006180 -0.001208 0.008031 -0.000990 0.001469 -0.000298 -0.005966 0.002625 -0.002675 -0.007651 0.009508 0.008759 -0.002190 -0.000452 0.001018 -0.007275 -0.008014 0.009109 0.000126 -0.005165 -0.006084 -0.006153 0.003394 0.000403 0.002662 
， -0.084016 -0.268353 0.112751 0.131606 0.267747 0.202145 0.140983 0.039096 0.133647 -0.082322 0.034171 0.175511 0.000193 0.142245 0.288289 -0.021575 -0.212870 0.055351 0.001571 -0.206641 0.044173 -0.171451 -0.199719 -0.148922 -0.084921 -0.002979 -0.161354 0.084511 0.009964 -0.074874 0.220145 -0.149086 -0.370997 0.075391 0.068695 0.054557 0.166918 -0.207688 0.147605 0.009089 0.069719 -0.085788 0.182483 -0.046985 0.063416 -0.263884 -0.051431 -0.051284 -0.125757 0.007723 
的 -0.013493 -0.266285 0.138829 0.088406 0.216536 0.088833 0.149426 -0.074363 0.266591 0.103497 0.037907 -0.002657 0.185266 0.170177 0.210094 0.004495 0.006145 0.256872 -0.010724 -0.272203 0.172877 -0.078950 -0.195248 -0.065496 -0.087796 -0.002000 -0.194374 0.058450 0.066791 -0.132387 0.154780 -0.025754 -0.297503 0.034945 0.098473 0.156391 0.109485 -0.213880 -0.068598 -0.066712 0.169170 -0.167599 0.189055 0.005520 0.013199 -0.239069 -0.173967 0.002154 0.062714 -0.042481 
。 -0.065404 -0.281322 0.152847 0.157530 0.201217 0.205073 0.114635 0.004931 0.173896 -0.072332 0.037312 0.110541 0.000794 0.164567 0.287439 -0.135397 -0.189849 0.122258 0.036365 -0.218481 0.067904 -0.110195 -0.211870 -0.129153 0.016466 0.070278 -0.158060 0.050070 0.036478 -0.097638 0.218157 -0.105143 -0.352633 0.099836 0.073517 0.075170 0.210049 -0.165742 0.041086 -0.044460 0.033139 -0.136531 0.180490 -0.045725 0.070770 -0.298211 -0.156638 -0.074599 -0.090784 -0.040388 
、 0.449735 -0.241043 0.328720 0.164438 0.112145 -0.029364 0.208858 -0.176351 0.102834 -0.125580 -0.023056 0.190501 0.237086 -0.024001 -0.017803 -0.570535 0.054477 0.199428 -0.237480 -0.237096 -0.150043 0.110675 -0.128416 0.303698 0.081876 -0.117619 0.043401 0.325238 0.287487 0.138299 0.404023 -0.174112 -0.389819 -0.201660 0.385984 0.349087 0.145431 -0.230172 0.489563 0.015919 -0.000928 0.034575 0.130751 0.213087 -0.006687 -0.681933 0.004185 -0.151713 -0.230260 -0.009538 
年 -0.132227 -0.301376 0.078740 -0.025298 0.247981 0.526094 -0.134951 0.144879 0.065355 -0.403069 0.057409 0.068202 -0.044366 0.344677 0.501927 -0.361455 -0.245191 -0.075899 0.357288 -0.408540 -0.048450 -0.007805 -0.167564 -0.418073 0.076195 0.450021 -0.228652 -0.107792 0.199509 -0.097023 0.186028 -0.121799 -0.401393 0.222878 0.094616 -0.145691 0.303715 -0.226068 -0.171682 -0.206594 -0.265348 -0.041538 0.165159 -0.249408 0.213990 -0.451901 -0.395497 -0.394400 -0.185508 0.010885 
在 -0.055735 -0.377210 0.043855 0.015364 0.179818 0.257447 0.140812 -0.079721 0.183958 -0.074492 -0.045969 -0.021084 0.119579 0.153630 0.231325 -0.063378 -0.188042 0.198095 0.247247 -0.156851 0.219481 0.030849 -0.303939 -0.202835 -0.122807 0.120519 -0.134151 -0.005425 0.089185 -0.120453 0.075798 -0.126825 -0.345042 0.066910 0.002952 0.054934 0.188904 -0.290347 -0.068432 -0.115375 0.072129 -0.077155 0.230847 -0.034738 0.041476 -0.281765 -0.103567 -0.105849 0.024441 -0.009120 
是 0.042937 -0.241193 0.095017 0.131379 0.120130 0.129802 0.144981 -0.088462 0.343210 0.135014 -0.107475 -0.013719 0.082011 0.102169 0.352426 -0.120792 -0.006164 0.379491 -0.088602 -0.333219 0.223860 -0.207441 -0.159815 0.134897 -0.030888 -0.112951 -0.176646 -0.077045 -0.025982 -0.302340 0.291826 0.060493 -0.360649 -0.115582 0.175032 0.130921 0.094038 -0.116510 -0.158178 -0.177012 0.044406 -0.328889 0.212104 0.128601 -0.030591 -0.214682 -0.187991 0.065041 0.009994 -0.130912 
（ -0.021795 -0.311250 -0.190077 0.156210 0.236759 0.318147 0.191349 0.151905 0.047532 -0.314743 -0.078975 0.030278 0.131654 0.327902 0.240721 -0.316661 0.113636 0.287511 -0.061079 -0.443810 -0.222219 -0.047074 -0.131761 0.212947 0.168538 0.022742 -0.108816 -0.129451 -0.147218 0.117850 0.128995 0.179787 -0.753496 -0.007696 0.247682 0.182999 0.115907 -0.248298 -0.084756 -0.031436 -0.197193 -0.216239 0.195260 0.139382 0.048944 -0.089881 -0.061321 -0.139018 -0.291245 -0.279365 
） -0.072231 -0.316700 -0.163942 0.111428 0.245837 0.309386 0.192362 0.142766 0.056594 -0.291826 -0.050940 0.023751 0.100949 0.301487 0.255378 -0.296701 0.088974 0.281667 -0.057976 -0.443831 -0.176923 -0.049894 -0.137309 0.202025 0.196892 0.021088 -0.095922 -0.127078 -0.136897 0.103412 0.099706 0.144460 -0.737774 0.010328 0.229722 0.144592 0.112879 -0.247322 -0.097775 -0.049957 -0.177045 -0.194412 0.217078 0.137945 0.039000 -0.076961 -0.065617 -0.156586 -0.274380 -0.287494 
为 -0.098808 -0.375511 0.030848 0.029625 0.193317 0.094838 0.177516 0.225661 0.137598 -0.077196 -0.007495 0.155500 -0.078908 0.146195 0.437182 -0.205069 -0.033780 0.138900 -0.217196 -0.403378 -0.205617 -0.396493 -0.219056 -0.097488 -0.011570 -0.083912 -0.268171 -0.162536 0.111232 0.031931 0.428370 -0.060849 -0.299653 -0.027116 0.167295 0.020694 0.254109 -0.005787 0.043799 0.024591 -0.105649 -0.180450 0.175836 -0.122147 0.045687 -0.251989 -0.010484 0.049964 -0.155557 -0.139518 
和 0.213823 -0.197218 0.242324 0.065658 0.216812 -0.052900 0.247728 -0.091370 0.192971 -0.000507 0.098032 -0.006624 0.260613 0.204339 0.021845 -0.190203 0.073535 0.340165 0.024093 -0.231617 0.039532 0.012655 -0.166647 0.029445 0.044380 0.002980 -0.151045 0.110524 0.067659 -0.088885 0.188152 -0.145861 -0.401039 -0.062669 0.120211 0.264960 0.168427 -0.171741 -0.026657 0.035803 0.094273 -0.051234 0.151903 0.065998 -0.014888 -0.379699 -0.182624 -0.074272 -0.112916 -0.030941 
了 -0.053611 -0.173020 0.172610 -0.104129 0.279738 0.173186 0.017924 -0.150107 0.088728 0.117420 0.111106 -0.031954 0.244462 0.265859 0.103493 -0.047899 -0.186015 0.248187 0.344618 0.051868 0.129476 0.104699 -0.122790 -0.208966 -0.048193 0.204320 -0.269353 -0.096708 0.117112 -0.071553 0.075533 -0.097330 -0.402652 0.145197 0.061643 0.114529 0.135863 -0.541612 -0.015193 0.009849 0.145969 -0.036056 0.125445 -0.171927 0.144320 -0.329624 -0.243576 0.023397 0.136403 0.134419 
月 0.098476 -0.678161 0.203172 -0.062480 0.046598 0.412446 0.021331 0.195169 -0.246350 -0.329448 -0.152450 -0.072136 -0.149654 0.331001 0.675303 -0.261636 -0.390511 -0.121245 0.407126 -0.356104 -0.405922 0.218903 -0.292697 -0.371742 -0.082227 0.619259 -0.214317 -0.039105 0.387520 -0.363337 0.185255 -0.151027 -0.276078 0.250221 -0.049334 -0.356216 0.135019 0.063713 -0.177689 -0.452801 0.006223 0.325591 0.047540 -0.438743 0.055837 -0.574985 -0.493102 -0.496421 -0.461485 0.169834 
与 0.076510 -0.232679 0.008605 0.318083 0.328566 -0.014061 0.193400 -0.064507 0.072924 0.087724 -0.059617 0.007308 0.168718 0.228233 0.052718 -0.192145 -0.088170 0.312574 -0.212345 -0.468135 0.080580 0.025006 -0.207367 -0.056824 -0.048449 -0.185570 -0.116323 0.048267 0.120261 -0.035644 0.107833 -0.351636 -0.257135 0.127019 0.138188 0.038309 0.072225 -0.243762 -0.003326 0.071363 0.134806 -0.065919 0.091705 -0.073282 -0.095416 -0.363683 -0.116997 -0.117071 -0.190421 0.005498 
》 0.058514 -0.299411 -0.576919 0.171573 -0.416396 0.566362 -0.172743 -0.422603 0.143624 0.331703 -0.324056 0.176340 0.339325 0.165313 0.354718 -0.288934 0.096173 -0.213905 0.073611 -0.245508 0.187068 -0.103824 -0.279371 0.416772 -0.376266 0.439884 -0.333749 0.136363 0.401632 0.137816 -0.079947 -0.341323 -0.472758 0.233454 0.407522 0.417249 -0.232873 -0.548367 -0.059405 0.351770 -0.124356 0.171392 -0.273250 -0.038976 0.652988 -0.728923 -0.495201 0.435225 -0.346518 -0.115417 
《 0.041923 -0.309021 -0.546229 0.170785 -0.432500 0.535870 -0.182931 -0.421001 0.155493 0.309721 -0.318675 0.165484 0.312430 0.144507 0.321871 -0.281900 0.072642 -0.216742 0.069396 -0.253047 0.180867 -0.084372 -0.290255 0.401147 -0.385476 0.451194 -0.339505 0.136136 0.441540 0.145351 -0.056733 -0.344690 -0.468343 0.236999 0.433847 0.446412 -0.230916 -0.534970 -0.063609 0.364001 -0.137610 0.149010 -0.289545 -0.044494 0.632360 -0.765901 -0.490688 0.423825 -0.342574 -0.069018 
于 -0.245763 -0.557175 0.061256 0.073062 0.158224 0.421270 -0.026906 0.093136 0.021437 -0.296021 -0.063578 -0.150083 -0.009253 0.284323 0.478914 -0.261318 -0.287799 0.193041 0.112551 -0.389400 0.100088 -0.138076 -0.300572 -0.210347 -0.101501 0.246771 -0.096768 0.017833 0.113604 -0.059286 0.203271 -0.202064 -0.165112 0.183605 0.119226 -0.141215 0.125084 -0.104048 -0.160759 -0.090645 -0.072082 -0.013852 0.394782 -0.099872 -0.045105 -0.346759 -0.257143 -0.312836 -0.153850 -0.055485 
有 0.129962 -0.260865 0.261810 0.240199 -0.031440 0.156667 0.326722 -0.019999 0.436208 0.003447 -0.101684 0.128662 -0.011576 0.168934 0.289042 0.023504 -0.072351 0.194740 -0.005749 -0.099663 0.035853 -0.276401 -0.309133 0.134403 0.007359 -0.139642 -0.145879 0.222600 0.030893 0.035602 0.201377 -0.173501 -0.183759 -0.042311 0.153702 0.164012 0.084400 -0.109792 0.216745 -0.158272 0.142645 -0.179782 0.115238 0.068540 0.007049 -0.255005 -0.187085 0.095533 0.083884 -0.112720

**Comment by lingmulhy** [comment]
![qq 20180316093940](https://user-images.githubusercontent.com/31685711/37501897-45b3e652-290b-11e8-96e7-0334265c5006.jpg)

**Comment by lingmulhy** [comment]
我明明也删除了word2vec文件的第一行的啊  还是有错

**Comment by lingmulhy** [comment]
试了各种删除第一行的方法  跑到那个位置还是照样报错   got shape [598455], but wanted [598455, 0]

**Comment by lingmulhy** [comment]
我把文件重新保存成txt文件也不管事

**Comment by lingmulhy** [comment]
唉

**Comment by wangxiaobaobao** [comment]
你好，我也是这样，删除了还是不行，麻烦分享一下如何解决的，谢谢！

**Comment by XuanlongQ** [comment]
最后怎么解决的？
