### ISSUE TITLE
是的，我又来了  现在又出现了问题

### ISSUE THREAD

**Issue by lingmulhy** [S-H-Y-GitHub/QA#24]
![qq 20180318155743](https://user-images.githubusercontent.com/31685711/37563895-99edb37c-2ac5-11e8-9e07-79c6ea011395.jpg)

**Comment by lingmulhy** [comment]
正在载入测试数据，大约需要一分钟...
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.215 seconds.
Prefix dict has been built succesfully.
测试数据加载完成
正在加载LSTM网络，大约需要三分钟...
加载完成！
重新训练，请保证计算机拥有至少8G空闲内存与2G空闲显存
正在准备训练数据，大约需要五分钟...
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    train()
  File "main.py", line 26, in train
    qTrain, aTrain, lTrain, qIdTrain = qaData.loadData(trainingFile, word2idx, unrollSteps, True)
  File "/home/428/lhy/QA-master/qaData.py", line 75, in loadData
    label = int(arr[2])
IndexError: list index out of range

**Comment by lingmulhy** [comment]
出现上述错误是因为啥呢  虚心求教

**Comment by S-H-Y-GitHub** [comment]
debug看一看吧，我也不知道是怎么回事

**Comment by lingmulhy** [comment]
广州市第五中学与其他示范性高中有哪些不同？	广州市第五中学位于中国广州市海珠区罗斗岗，成立于1951年，是中华人民共和国成立后，广州市人民政府创办的第一所公立中学。	0
广州市第五中学与其他示范性高中有哪些不同？	1994年被首批命名为“广东省一级学校”。	0
广州市第五中学与其他示范性高中有哪些不同？	目前为广州市24所首批国家级示范性高中之一。	0
广州市第五中学与其他示范性高中有哪些不同？	1951年，广州市第五中学建校，成为中华人民共和国成立后，广州市人民政府创办的第一所公立中学。	0
广州市第五中学与其他示范性高中有哪些不同？	2000年12月，被广州市人民政府定为广州市24所首批创办国家级示范性高中之一	0
广州市第五中学与其他示范性高中有哪些不同？	2003年9月，广州市第十九中学整体并入	0
广州市第五中学与其他示范性高中有哪些不同？	2003年，在教育体制改革下，广州市第五中学决定扩招。	0
广州市第五中学与其他示范性高中有哪些不同？	2005年7月，校本部最后一届初三学生毕业，至此五中校本部全部转为高中；同时原东校区学生也悉数毕业，目前东校区成为广州市实验技工学校的南校区。	0
广州市第五中学与其他示范性高中有哪些不同？	2010年9月，校本部重新招收初中学生，金碧校区停止招生，当时在金碧校区就读的初二、初三学生继续在金碧校区就读，直至毕业，至此五中校本部转为完全中学。	0
广州市第五中学与其他示范性高中有哪些不同？	2011年9月，初中第二年在校本部招生，且金碧校区交由广州市第九十七中学管理，广州市第五中学初三学生与广州市第九十七中学高一学生同时在金碧校区学习。	0
广州市第五中学与其他示范性高中有哪些不同？	2012年7月，金碧校区最后一届初三学生毕业，至此金碧校区全面移交广州市第九十七中学，全校所有学生均在校本部学习，从此五中只剩下校本部一个校区。	0
广州市第五中学与其他示范性高中有哪些不同？	广州市第十九中学并入后，在原广州市第十九中学校址（同在南村路上，只是斜对面）设有东校区；在海珠区工业大道南第三金碧花园设有初中校区，或称金碧校区，初中部占地27000平方米。	0
广州市第五中学与其他示范性高中有哪些不同？	校本部当时只设有高中部，高中部占地64233平方米，初中部则在金碧校区教学。	0
广州市第五中学与其他示范性高中有哪些不同？	由于教育资源调整，金碧校区从2011年9月起交由广州巿第九十七中学管理。	0
广州市第五中学与其他示范性高中有哪些不同？	由2010学年起，新初一将于校本部就读。	0
广州市第五中学与其他示范性高中有哪些不同？	原初一、初二则继续留在金碧校区，至初中毕业。	0
广州市第五中学与其他示范性高中有哪些不同？	目前金碧校区已成为广州市第九十七中学高中校区。	0
广州市第五中学与其他示范性高中有哪些不同？	在2011学年，广州市第五中学初三级和广州市九十七中学高一级同时在金碧校区教学，而广州市第五中学初一、初二级和高中则在广州市第五中学高中部教学。	0
广州市第五中学与其他示范性高中有哪些不同？	目前所有年级均在校本部教学。	0
广州市第五中学与其他示范性高中有哪些不同？	与其他示范性高中不同，五中高中部在2011年9月前尚有部分课室及所有学生宿舍、饭堂无设有空调，在夏天上课及睡觉是十分难熬的。	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	美国天文学会标志    美国天文学会（American Astronomical Society，缩写为AAS）是由美国专业的天文学家和有兴趣的个人组成的天文团体，总部设在华盛顿特区。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	美国天文学会成立的首要目标是要将天文学和其他领域的科学紧密结合，其次是要经由政治上的游说，让成员在国会殿堂上发声，和基层的活动提升天文教育。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	美国天文学会在乔治·埃勒里·海耳的努力下创立于1899年，学会章程由海尔、乔治·康斯托克、爱德华·莫利、西蒙·纽康和爱德华·皮克林撰写，这些起草人加上另外的4人组成第一届执行委员会，并由纽康担任主席，创始的会员有114人。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	学会最早的名称是“美国天体物理学会”，之后曾一度称为“天文和天体物理学会”，到1915年才决定现在所用的名称。[1]	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	现在的美国天文学会的会员超过6,500人，并有5个分支部门：	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	行星科学（1968年）	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	动力天文学（1969年）	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	高能天文物理学（1969年）	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	太阳物理学（1969年）	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	天文学史（1980年）	1
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	因为天文学的范围广泛，在总章程的规范下，美国天文学会之下还设了几个分支部门，各自在不同的领域和相关的科学内运作。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	除了参与总会的会议，个分支也会召开自己的会议。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	这些分支部门主要的研究除兴趣是：	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	行星科学（DPS）：支援行星科学和探测太阳系。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	动力天文学（DDA）：在宇宙学尺度下，支援从太阳系到星系、星系团等天文学系统的动力学的研究，包括轨道、演变和历史。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	高能天文物理学（HEAD）：支援有关于高能量事件、粒子、量子、相对论的 引力场等与天体物学的宇宙相关的现象和知识。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	天文学史（HAD）：在天文学的领域内，支援有关于天文历史的研究，并且研究使用历史上的天文记录解决目前天文学上的问题。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	太阳物理学（SPD）：支援天文物理学对太阳和太阳与地球和太阳系之间互动的研究。	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	美国天文学会和他的分支部门每年都颁发许多知名的奖项，广为社会大众所知的有：	0
美国天文学会现在有哪几个分支部门，分别是哪一年创立的？	亨利·诺利斯·罗素讲座：天文学界的终身成就奖。	0
武汉大学国学院开设了哪些主要的课程？	武汉大学国学院是武汉大学的一个学院，位于主校区，创建于2010年。[1]	0
武汉大学国学院开设了哪些主要的课程？	国学院的成立使得武汉大学成为中国国内少数拥有国学完整培养体系的大学。	0

**Comment by lingmulhy** [comment]
这是数据格式  数据格式是对的吗

**Comment by S-H-Y-GitHub** [comment]
看上去没问题呀

**Comment by lingmulhy** [comment]
是吧  唉  看来我真是命途多舛啊  麻烦您了

**Comment by S-H-Y-GitHub** [comment]
祝好运~

**Comment by lingmulhy** [comment]
谢谢   you too

**Comment by yy952** [comment]
请问你现在弄好了吗

**Comment by Wc30** [comment]
请问我在lstm这里就已经报错了
