### ISSUE TITLE
给定一个test

### ISSUE THREAD

**Issue by tinnarey** [S-H-Y-GitHub/QA#28]
请问，可以用你这个模型测试我自己给定的测试集吗？测试集按照你这个形式，得到的结果是可以判断我的问题所对应的几个答案，哪个是对的吗？谢谢~

**Comment by yiduobaozhi** [comment]
那个我也有一个问题，就是我重现了你这个代码，然后你说的12个小时，我跑了36小时了。。step现在已经12360步，但是现在还没跑完，请问具体差不多多少step呢

**Comment by S-H-Y-GitHub** [comment]
这个是你自己设置的，看看什么时候收敛什么时候结束就行了

**Comment by yiduobaozhi** [comment]
也就是说我现在如果按照你源代码跑的话，没有设置收敛就永远不会结束了吗。。我的drop out和您的一样都是1

**Comment by tinnarey** [comment]
大概3万多个step就会停止，我跑了两天。

**Comment by tinnarey** [comment]
没有时间换其他的模型了😂😂😂我的数据格式设置和你一样也不行，必须纬度都要一样，只能改代码了。。。😭😭😭

**Comment by yiduobaozhi** [comment]
你是参加了什么比赛吗

**Comment by S-H-Y-GitHub** [comment]
用不了那么久，看着收敛了就能停掉了，我记得好像是每次都存了检查点的，你可以看看这个版本的代码里有没有
我没有用dropout，1.0的话估计是写反了，应该是keepprob

**Comment by tinnarey** [comment]
嗯呢，。。能不能给个邮箱私聊私聊？给点建议。。。。

**Comment by yiduobaozhi** [comment]
lstm.keep_prob: dropout  ，代码里面是这样的，然后dropout=1.0，检查点没看到，所以现在不知道具体还要跑多久

**Comment by yiduobaozhi** [comment]
那个515004768@qq.com，邮箱私聊

**Comment by tinnarey** [comment]
为啥你的测试集也是带标签呢。。。。这个问题让我很痛苦啊 测试集也必须要有正确的标记，，，

**Comment by tinnarey** [comment]
可以了  只需要把自己的测试集 按照作者的 \t分割句子   前面没注意数据格式 居然是\t  我以为是空格。。。
