### ISSUE TITLE
got shape [598455], but wanted [598455, 0].

### ISSUE THREAD

**Issue by zhaoshuyang** [S-H-Y-GitHub/QA#4]
请问，跑到最后出来这句“got shape [598455], but wanted [598455, 0].”也不报错，是什么意思

**Comment by S-H-Y-GitHub** [comment]
没见过，你确定没有改我的代码而且依赖项的版本都一样吗？

**Comment by LMdeLiangMi** [comment]
你好！一样的问题，请问您解决了吗

**Comment by LMdeLiangMi** [comment]
tensorflow是1.2.1的，jieba是0.38，word2vec文件是自己在网上下载的，data文件是今天更新前本开源项目自带的，报这个错……got shape [598455], but wanted [598455, 0]

```
    trainingFile = "data/training.data"
    developFile = "data/develop.data"
    testingFile = "data/testing.data"
    resultFile = "predictRst.score"
    saveFile = "newModel/savedModel"
    trainedModel = "trainedModel/savedModel"
    embeddingFile = "word2vec/zhwiki_2017_03.sg_50d.word2vec"
```
请问能提供下这些data吗？

**Comment by S-H-Y-GitHub** [comment]
那么所有的环境都是一样的，居然会出错，我去跑跑看看

**Comment by S-H-Y-GitHub** [comment]
我跑了一会，无法复现这个问题，整个过程都是正常的。看报错是张量的shape有问题，可以调试一下代码看看是哪个地方出错

**Comment by LMdeLiangMi** [comment]
` lstm = QaLSTMNet(batchSize, unrollSteps, embedding, embeddingSize, rnnSize, margin)`
跑到这里报错的

**Comment by LMdeLiangMi** [comment]
`0.291779, 0.044742, -0.922261, -0.35683, 0.306225, -0.717964, 0.338777, 0.23025, -0.304165, 0.075, -0.12885, -0.351377, 0.214538, -0.446979, 1.188447, -0.614745, 0.112657, 0.084754, 0.593094, -0.637226, 0.5725, -0.58602, -0.071747, -0.14988, -0.063176, 0.218723, 0.662518, -0.869088, 0.595149, -0.284111, 0.329275, 0.716735, 0.155025, 0.189422, 0.433483, -1.153803, -1.346856, -0.125522, -0.041175, 0.348217], [-0.496101, -0.851788, 0.156552, 0.312364, 0.392472, 0.206131, 0.403157, -0.29031, 0.763209, 1.157545, 1.26221, -0.097943, 0.488298, -0.607819, 0.072464, -0.25858, -0.487426, 0.595976, -0.51106, -0.125968, -0.298714, 0.567029, -0.679832, -0.03967, -0.045916, -0.732261, -0.5691, -0.542687, -0.13764, -0.148888, 0.461572, -0.675791, -0.202226, 0.227553, -0.016537, 0.805945, 0.223084, 0.166775, -0.814434, -0.652344, -0.321782, 0.307222, 0.471198, 0.198593, 0.178953, 0.01718, -0.534217, 0.491728, 0.345398, -0.402825], [-0.109182, -1.04468, -0.443628, -0.212803, 0.154779, 0.094147, 0.407804, 0.52335, 0.967962, 1.310945, 1.691452, -0.41803, 0.643319, -0.10488, 0.331624, 0.228548, -0.568821, 0.522153, -0.480846, -0.261651, -0.327075, 0.036537, -0.68047, 0.404303, 0.192987, -0.040602, 0.060227, -0.366517, 0.017119, -0.107629, 0.651498, -0.095877, -0.257343, 0.027402, -0.015883, 0.074849, -0.409343, -0.158158, -0.756825, -0.924295, -0.08168, 0.003747, 0.729945, 0.140108, -0.10967, -0.194657, -0.161658, -0.058256, 0.190219, -0.04339], [-0.018677, -0.624376, 0.161201, -0.071621, 0.333878, -0.023625, -0.228563, 0.397908, 0.502866, 0.863872, 1.698446, -0.291771, 0.411021, -0.544957, 0.552331, 0.49162, -0.354171, 0.605605, -0.331464, -0.307178, 0.048404, 0.064014, -0.902935, 0.361013, 0.190309, -0.574293, 0.125801, -0.291425, -0.209483, -0.064536, 0.378647, -0.01305, -0.881323, -0.112065, -0.008485, 0.195728, -0.090683, -0.199238, -0.527464, -0.917339, 0.001278, 0.118985, 0.417046, 0.202766, 0.109357, 0.234372, -0.2567, -0.004855, 0.491701, -0.395351]] - got shape [598455], but wanted [598455, 0].`

**Comment by LMdeLiangMi** [comment]
我是ubuntu16.04

**Comment by S-H-Y-GitHub** [comment]
呃。。。。那是个构造函数，里面还有代码的。。。
用get_shape()可以拿到那些变量的shape，看看是哪个变量出了问题

**Comment by LMdeLiangMi** [comment]
恩我调试下……请问可以把您刚才运行的项目文件夹压个包上传到百度云吗？

**Comment by S-H-Y-GitHub** [comment]
clone就能拿到了嘛

**Comment by LMdeLiangMi** [comment]
![default](https://user-images.githubusercontent.com/13929748/30651822-5e845ece-9e59-11e7-8bac-6ff13789e97e.png)

**Comment by LMdeLiangMi** [comment]
现在的项目木有data文件夹吧……还有word2vec文件，我自己下载的文件不知道靠不靠谱

**Comment by S-H-Y-GitHub** [comment]
嗯。。。embedding出了问题，发几行word2vec文件看看？

**Comment by LMdeLiangMi** [comment]
![default](https://user-images.githubusercontent.com/13929748/30652174-46a0abea-9e5a-11e7-995a-d01af19b019c.png)
定位到这一句……
` tfEmbedding = tf.Variable(tf.to_float(self.embeddings), trainable=True, name="W")`

word2vec文件
```
598454 50
</s> 0.008005 0.008839 -0.007661 -0.006556 0.002733 0.006042 0.001882 0.000423 -0.007207 0.004437 -0.008713 0.002499 -0.001503 -0.001914 -0.006631 -0.003764 0.005159 0.006051 0.005938 0.003195 0.003090 -0.007605 -0.008192 0.009939 0.007603 0.006180 -0.001208 0.008031 -0.000990 0.001469 -0.000298 -0.005966 0.002625 -0.002675 -0.007651 0.009508 0.008759 -0.002190 -0.000452 0.001018 -0.007275 -0.008014 0.009109 0.000126 -0.005165 -0.006084 -0.006153 0.003394 0.000403 0.002662 
， -0.084016 -0.268353 0.112751 0.131606 0.267747 0.202145 0.140983 0.039096 0.133647 -0.082322 0.034171 0.175511 0.000193 0.142245 0.288289 -0.021575 -0.212870 0.055351 0.001571 -0.206641 0.044173 -0.171451 -0.199719 -0.148922 -0.084921 -0.002979 -0.161354 0.084511 0.009964 -0.074874 0.220145 -0.149086 -0.370997 0.075391 0.068695 0.054557 0.166918 -0.207688 0.147605 0.009089 0.069719 -0.085788 0.182483 -0.046985 0.063416 -0.263884 -0.051431 -0.051284 -0.125757 0.007723 
的 -0.013493 -0.266285 0.138829 0.088406 0.216536 0.088833 0.149426 -0.074363 0.266591 0.103497 0.037907 -0.002657 0.185266 0.170177 0.210094 0.004495 0.006145 0.256872 -0.010724 -0.272203 0.172877 -0.078950 -0.195248 -0.065496 -0.087796 -0.002000 -0.194374 0.058450 0.066791 -0.132387 0.154780 -0.025754 -0.297503 0.034945 0.098473 0.156391 0.109485 -0.213880 -0.068598 -0.066712 0.169170 -0.167599 0.189055 0.005520 0.013199 -0.239069 -0.173967 0.002154 0.062714 -0.042481 
。 -0.065404 -0.281322 0.152847 0.157530 0.201217 0.205073 0.114635 0.004931 0.173896 -0.072332 0.037312 0.110541 0.000794 0.164567 0.287439 -0.135397 -0.189849 0.122258 0.036365 -0.218481 0.067904 -0.110195 -0.211870 -0.129153 0.016466 0.070278 -0.158060 0.050070 0.036478 -0.097638 0.218157 -0.105143 -0.352633 0.099836 0.073517 0.075170 0.210049 -0.165742 0.041086 -0.044460 0.033139 -0.136531 0.180490 -0.045725 0.070770 -0.298211 -0.156638 -0.074599 -0.090784 -0.040388 
、 0.449735 -0.241043 0.328720 0.164438 0.112145 -0.029364 0.208858 -0.176351 0.102834 -0.125580 -0.023056 0.190501 0.237086 -0.024001 -0.017803 -0.570535 0.054477 0.199428 -0.237480 -0.237096 -0.150043 0.110675 -0.128416 0.303698 0.081876 -0.117619 0.043401 0.325238 0.287487 0.138299 0.404023 -0.174112 -0.389819 -0.201660 0.385984 0.349087 0.145431 -0.230172 0.489563 0.015919 -0.000928 0.034575 0.130751 0.213087 -0.006687 -0.681933 0.004185 -0.151713 -0.230260 -0.009538 
年 -0.132227 -0.301376 0.078740 -0.025298 0.247981 0.526094 -0.134951 0.144879 0.065355 -0.403069 0.057409 0.068202 -0.044366 0.344677 0.501927 -0.361455 -0.245191 -0.075899 0.357288 -0.408540 -0.048450 -0.007805 -0.167564 -0.418073 0.076195 0.450021 -0.228652 -0.107792 0.199509 -0.097023 0.186028 -0.121799 -0.401393 0.222878 0.094616 -0.145691 0.303715 -0.226068 -0.171682 -0.206594 -0.265348 -0.041538 0.165159 -0.249408 0.213990 -0.451901 -0.395497 -0.394400 -0.185508 0.010885 
在 -0.055735 -0.377210 0.043855 0.015364 0.179818 0.257447 0.140812 -0.079721 0.183958 -0.074492 -0.045969 -0.021084 0.119579 0.153630 0.231325 -0.063378 -0.188042 0.198095 0.247247 -0.156851 0.219481 0.030849 -0.303939 -0.202835 -0.122807 0.120519 -0.134151 -0.005425 0.089185 -0.120453 0.075798 -0.126825 -0.345042 0.066910 0.002952 0.054934 0.188904 -0.290347 -0.068432 -0.115375 0.072129 -0.077155 0.230847 -0.034738 0.041476 -0.281765 -0.103567 -0.105849 0.024441 -0.009120 
是 0.042937 -0.241193 0.095017 0.131379 0.120130 0.129802 0.144981 -0.088462 0.343210 0.135014 -0.107475 -0.013719 0.082011 0.102169 0.352426 -0.120792 -0.006164 0.379491 -0.088602 -0.333219 0.223860 -0.207441 -0.159815 0.134897 -0.030888 -0.112951 -0.176646 -0.077045 -0.025982 -0.302340 0.291826 0.060493 -0.360649 -0.115582 0.175032 0.130921 0.094038 -0.116510 -0.158178 -0.177012 0.044406 -0.328889 0.212104 0.128601 -0.030591 -0.214682 -0.187991 0.065041 0.009994 -0.130912 
```

**Comment by S-H-Y-GitHub** [comment]
第一行那俩是啥啊，删了试试

**Comment by LMdeLiangMi** [comment]
开始训练了，但是感觉内存不够啊……
![default](https://user-images.githubusercontent.com/13929748/30652887-19408588-9e5c-11e7-880c-5d9922ea5de9.png)

**Comment by S-H-Y-GitHub** [comment]
不要把issue当论坛。。。。

**Comment by lingmulhy** [comment]
嗯
