### ISSUE TITLE
咨询模型文件分享

### ISSUE THREAD

**Issue by LMdeLiangMi** [S-H-Y-GitHub/QA#5]
一开始运行发现少了个文件，在网上下到的word2vec文件，二百多M
http://www.cnblogs.com/robert-dlut/p/6586621.html
再运行，报了一堆数字……不知道是不是爆了内存，机器有8G内存和4G显存，但是空闲内存没有8G这么多，可以调整相关参数降低内存占用吗？
```
    dropout = 1.0
    learningRate = 0.4  # 学习速度
    lrDownRate = 0.5  # 学习速度下降速度
    lrDownCount = 4  # 学习速度下降次数
    epochs = 20  # 每次学习速度指数下降之前执行的完整epoch次数
    batchSize = 20  # 每一批次处理的<b>问题</b>个数

    rnnSize = 100  # LSTM cell中隐藏层神经元的个数
    margin = 0.1  # M is constant margin

    unrollSteps = 100  # 句子中的最大词汇数目
    max_grad_norm = 5  # 用于控制梯度膨胀，如果梯度向量的L2模超过max_grad_norm，则等比例缩小

    allow_soft_placement = True  # Allow device soft device placement
    gpuMemUsage = 0.75  # 显存最大使用率
    gpuDevice = "/gpu:0"  # GPU设备名

``` 
调低batchsize？

最后，请问可以分享下训练好的模型吗？
谢谢！

**Comment by S-H-Y-GitHub** [comment]
爆内存不大可能，毕竟有虚拟内存在
爆显存也不大可能，我的2G都没问题，那个batchsize你反而可以调高，减少IO开销，加速训练过程
调参不能降低内存占用，必须改模型，可以试试把embedding层独立出来
训练好的模型我也找不着了，当初交了作业就再没碰过

**Comment by LMdeLiangMi** [comment]
got shape [598455], but wanted [598455, 0]
报的这个错，摸不着头脑……我tensorflow这些库版本是符合的……然后为啥删了data文件夹呀？

**Comment by S-H-Y-GitHub** [comment]
这个问题请去 #4 中讨论
